#if !canImport(ObjectiveC)
import XCTest

extension XMLParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLParsingTests = [
        ("testBooks", testBooks),
        ("testCatalog", testCatalog),
        ("testCD", testCD),
        ("testMenu", testMenu),
        ("testNote", testNote),
        ("testPlant", testPlant),
        ("testRSS", testRSS),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XMLParsingTests.__allTests__XMLParsingTests),
    ]
}
#endif
